version: '3.7'

services:
  es_mysql:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_esp22
      MYSQL_PASSWORD: root


  springboot-docker-compose-app-container:
    image: springboot-docker-compose-app:1
    restart: on-failure
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - /complete
    ports:
      - "8082:8082"
    depends_on:
      - kafka
      - es_mysql
    links:
      - kafka:kafka
      - es_mysql:es_mysql
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://es_mysql:3306/db_esp22?user=root&password=root
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update


  zookeeper:
      image: wurstmeister/zookeeper
      ports:
        - "2181:2181"

  kafka:
    # build: .
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    expose:
      - "9092"
    depends_on:
      - zookeeper
    links:
      - zookeeper:zookeeper
    container_name: kafka
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181


    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  producer:
    build: ../../Producer/./
    image: producer-python
    restart: on-failure
    ports:
      - "9091:9092"
    depends_on:
      - kafka

 # esp22_logstash:
 #    build:
 #      context: logstash/
 #    container_name: esp22_logstash
 #      volumes:
 #        - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
 #        - ./logstash/pipeline:/usr/share/logstash/pipeline:ro
 #      ports:
 #        - "22005:22005/tcp"

  # db:
  #   image: mysql:5.6
  #   restart: always
  #   environment:
  #     MYSQL_DATABASE: 'demo'
  #     # So you don't have to use root, but you can if you like
  #     MYSQL_USER: 'demo_user'
  #     # You can use whatever password you like
  #     MYSQL_PASSWORD: 'demo_pass'
  #     # Password for root access
  #     MYSQL_ROOT_PASSWORD: 'password'
  #   ports:
  #     # <Port exposed> : < MySQL Port running inside container>
  #     - "3307:3306"
  #   expose:
  #     # Opens port 3306 on the container
  #     - "3307"
  #     # Where our data will be persisted
  #   volumes:
  #     - my-db:/var/lib/mysql
#
#   #adminer:
#   #  image: adminer
#   #  restart: always
#   #  ports:
#   #    - 8080:8080
#
# volumes:
#   my-db:
